rotateMatrix : rotateMatrix.o rotate.o
	gcc -o rotateMatrix rotateMatrix.o rotate.o
rotateMatrix.o : rotateMatrix.c
	gcc -c -pedantic -Wall -Werror -std=gnu99 rotateMatrix.c
rotate.o : rotate.c
	gcc -c -pedantic -Wall -Werror -std=gnu99 rotate.c	
